volumes:
  postgres_data:
  imposm_cache:
  imposm_expiry:
  imposm_diff:

services:
  db:
    build:
      context: .
      dockerfile: db/Dockerfile
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  imposm:
    build: imposm
    volumes:
      - imposm_cache:/imposm-cache
      - imposm_expiry:/imposm-expiry
      - imposm_diff:/imposm-diff
    command:
      - run
      - -expiretiles-dir
      - /imposm-expiry
      - -cachedir
      - /imposm-cache
      - -diffdir
      - /imposm-diff
      - -mapping
      - /mapping.json
      - -connection
      - "postgis://osm:osm@db/osm"
  
  tegola:
    build: tegola
    environment:
      DB_URI: "postgres://osm:osm@db:5432/osm"
    ports:
      - "8080:80"